### ISSUE TITLE
kpm restore fails to proceed to fallback sources when there is an error in the first listed feed

### ISSUE THREAD

**Issue by Praburaj** [aspnet/KRuntime#1018]
_From @itsananderson on May 13, 2014 15:51_

I was walking through the getting started section, and I noticed an exception being thrown from the `kpm restore` step.

```
Attempting to resolve dependency System.Console >= 4.0.0.0
  OK https://my-feed.cloudapp.net/api/v2/FindPackagesById()?Id='System.Console' 448ms
Warning: FindPackagesById: System.Console
  '=' is an unexpected token. The expected token is ';'. Line 21, position 78.
```

(I've sanitized the actual feed URL, but I'm a Microsoft employee if that helps)

My guess is that one of three things is happening:

1. kpm doesn't know how to negotiate authentication with the private NuGet feed
1. The private feed needs an update to work with kpm, and kpm doesn't gracefully handle communicating with old feeds
1. The feed simply doesn't contain the "System.Console" package, and kpm doesn't gracefully handle missing packages.

Other details:

KRE builds tested (both reproduced issue)

```
0.1-alpha-build-0421 svr50   x86          C:\Users\me\.kre\packages
0.1-alpha-build-0425 svr50   x86          C:\Users\me\.kre\packages
```

Pretty sure these aren't relevant, but:

* Windows 8.1 update
* IIS 8.5

Here's  a full dump of console output, and the actual response I get from the NuGet feed when I run the `Id='System.Console'` query in the browser: https://gist.github.com/itsananderson/3f6c8ec3fb1bb8699a91

_Copied from original issue: aspnet/Home#15_

**Comment by davidfowl** [comment]
That's by design. Use --ignore-failed-sources to ignore sources that may not be reachable or failing etc
