### ISSUE TITLE
Ability to exclude projects via global.json

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/KRuntime#1024]
In Visual Studio we would like to enable ```Exclude Project``` which would do the following.

 1. Remove the project from Solution Explorer
 1. Remove the project from the list of projects being built

To facilitate this I'm proposing a new entry in ```global.json``` as follows.

```
{
    "sources": [ "src", "test", "../../bugs2/ClassLibrary1/src" ],
    "sourcesExclude": [
        "src/MyCoolProject",
        "test/MyCoolProjectTests"
    ]
}
```

I don't believe that we need to support expressions like ```**``` or ```*```.

When a project is excluded in Visual Studio we will write an entry into ```sourcesExclude``` and the project will be removed from the solution.

When an existing project is added to the solution if there is a corresponding entry in ```sourcesExclude``` that will be removed and the project will be added to the solution.

Thoughts?

cc @davidfowl @glennc @danroth27 @mayurid

**Comment by lucamorelli** [comment]
Is it possible to reintroduce the command Exclude from Project in the solution project to remove a single or a Group of items with Solution Explorer? Actually I have to mode manually the files outside the solution directory

**Comment by sayedihashimi** [comment]
I chatted with some folks and it looks like we don't need this feature. Instead what we will do is what happens to C# projects today. When a project is excluded from the solution the following will happen. I will close this item now.

 1. References to the project are removed from other projects in the solution
 1. Project is removed from solution explorer

@lucamorelli if you mean excluding files from a project, we are working on that feature right now. In a future release you'll be able to exclude files from compile and publish directly from solution explorer.
