### ISSUE TITLE
Allow kvm to manage KRE versions for other platforms

### ISSUE THREAD

**Issue by bgourlie** [aspnet/KRuntime#1073]
I'd like it if kvm on Linux/OS X were able to pull down the Windows KRE, or kvm on Windows pull down the mono KRE.  The obvious use-case for this is building and packing an asp.net app on one platform that targets another.

I have this mostly working already -- building and deploying to Azure from a linux vm on travis-ci, but I hack it by manually copying `KRE-CLR-x86.1.0.0-*` to `.kre/packages/`.  If I were able to automate this entirely through kvm, it would be most excellent.

**Comment by Praburaj** [comment]
This issue was moved to aspnet/kvm#136
