### ISSUE TITLE
1.0.0-beta2 does not build (on Linux)

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/KRuntime#1092]
In my yocto Linux layer, I build KRuntime from source. The beta2 release, however, does not succeed out of the box, because of the Roslyn API updates. If I patch the sources with fbf7882 and ad60760, everything works.

Are there any plans to "shield" the build system against breaking updates in the build dependencies in the future?

**Comment by davidfowl** [comment]
When we're out of prerelease mode but not until then. Another thing we need to do is pin the versions of tags so that you get the right set of dependencies
