### ISSUE TITLE
Rename --port flag to --server flag and KRE_COMPILATION_SERVER_PORT to KRE_COMPILATION_SERVER

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KRuntime#538]
Today we support the runtime passing a flag that allows it to get bits from the design time host via the --port flag and KRE_COMPILATION_SERVER_PORT. We should change the names of these things from:

--port to --server
KRE_COMPILATION_SERVER_PORT to KRE_COMPILATION_SERVER

We'll likely experiment/support different transports (tcp/named pipes etc)

**Comment by muratg** [comment]
No
