### ISSUE TITLE
Use AppDomain.ApplyPolicy(assemblyName) before loading assemblies on CLR

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KRuntime#563]
Today we use this hack to load retarget able assemblies:

https://github.com/aspnet/KRuntime/blob/4fbf1fbfff08e131bb4d5cd737f1f4be75702996/src/klr.hosting.shared/RuntimeBootstrapper.cs#L174

http://msdn.microsoft.com/en-us/library/system.appdomain.applypolicy(v=vs.110).aspx

We're supposed to apply this policy before calling into the loaders.

**Comment by troydai** [comment]
Fixed in https://github.com/aspnet/KRuntime/commit/bb3cdbdb67ca04366fcb9a04e56d0dc05752debb
