### ISSUE TITLE
If project name contains Arabic characters, kpm build gives ArgumentException Illegal characters on path

### ISSUE THREAD

**Issue by balachir** [aspnet/KRuntime#706]
1. New Empty app : EmptyAppWebسةوڐڔ٩ (app name contains Arabic charaters)
2. Open property pages : choose options to 'Produce outputs on build'
3. Build

ACTUAL

![image](https://cloud.githubusercontent.com/assets/8246794/4536409/0824285c-4dc6-11e4-8e95-cd1b38d269ae.png)

1>------ Build started: Project: EmptyAppWebسةوڐڔ٩, Configuration: Debug Any CPU ------
1>  System.ArgumentException: Illegal characters in path.
1>     at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
1>     at System.Security.Permissions.FileIOPermission.CheckIllegalCharacters(String[] str)
1>     at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
1>     at System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String[] pathList, Boolean checkForDuplicates, Boolean needFullPath)
1>     at System.IO.Path.GetFullPath(String path)
1>     at Microsoft.Framework.PackageManager.BuildManager.Normalize(String projectDir)
1>     at Microsoft.Framework.PackageManager.BuildManager..ctor(IServiceProvider hostServices, BuildOptions buildOptions)
1>     at Microsoft.Framework.PackageManager.Program.<>c__DisplayClass3.<Main>b__12()
1>     at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
1>     at Microsoft.Framework.PackageManager.Program.Main(String[] args)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AspNet\Microsoft.Web.AspNet.targets(133,5): error MSB3073: The command ""C:\Users\balach\.kre\packages\kre-clr-x86.1.0.0-beta1-10492\bin\klr.exe" "C:\Users\balach\.kre\packages\kre-clr-x86.1.0.0-beta1-10492\bin\lib\Microsoft.Framework.PackageManager\Microsoft.Framework.PackageManager.dll" build "C:\Users\balach\Documents\Visual Studio 14\Projects\EmptyAppWebسةوڐڔ٩\src\EmptyAppWebسةوڐڔ٩" --configuration Debug" exited with code 1.
========== Build: 0 succeeded or up-to-date, 1 failed, 0 skipped ==========

EXPECTED
Build should work -- VS supports localized project names

**Comment by Praburaj** [comment]
Does not reproduce now. @balachir do you see this reproduce still?

**Comment by Praburaj** [comment]
Btw I tried `kpm build` from command line.

**Comment by Praburaj** [comment]
I can reproduce this from VS. But not from command line. I tried both `kpm build` and `kpm pack` from command for the same project and they seem to work. And I also verified that the `kpm pack` output contains the correct app folder name with these arabic characters as it is. Can this be a tooling issue?

**Comment by Praburaj** [comment]
Some more investigation details. 

After trying from the command line trials I , @ChengTian & @balachir created a console application and executed the same commands that VS executes. This seems to run fine on a console app as well. This makes us think this is a tooling issue. 

```
using System;
using System.Diagnostics;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                var process = Process.Start(new ProcessStartInfo()
                {
                    FileName = @"D:\Users\user\.kre\packages\kre-clr-x86.1.0.0-beta2\bin\klr.exe",
                    Arguments = @"--appbase ""d:\users\user\documents\visual studio 2015\Projects\EmptyAppWebسةوڐڔ1٩\src\EmptyAppWebسةوڐڔ1٩"" ""D:\Users\user\.kre\packages\kre-clr-x86.1.0.0-beta2\bin\lib\Microsoft.Framework.PackageManager\Microsoft.Framework.PackageManager.dll"" build ""d:\users\user\documents\visual studio 2015\Projects\EmptyAppWebسةوڐڔ1٩\src\EmptyAppWebسةوڐڔ1٩"" --configuration Debug --out ""..\..\artifacts\bin\EmptyAppWebسةوڐڔ1٩"""
                });

                process.WaitForExit();

                Console.WriteLine(process.ExitCode);
                Console.Read();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
        }
    }
}
```

@balachir @PradeepKadubandi - could you take this bug for investigation from tooling perspective. If you would like to bug in tooling repo and close this bug feel free to do so.

**Comment by balachir** [comment]
I've re-activated the bug on the tooling side for us to investigate

**Comment by ChengTian** [comment]
Moved to tooling bug repo.

**Comment by okletsgo** [comment]
Same to me. Bug I have just only English characters.
