### ISSUE TITLE
The web.cmd made by publishing from VS doesn't tell you the port, nor are you told the point in the command line 

### ISSUE THREAD

**Issue by shanselman** [aspnet/KRuntime#857]
The web.cmd made by publishing from VS doesn't tell you the port, nor are you told the point in the command line.

A console message should say something like "started on http://localhost:5000"

I realize it's in project.json but there's no way for the user to know that 

Useful for demos. @coolcsh

**Comment by muratg** [comment]
See hosting bug

**Comment by shanselman** [comment]
This seems to have regressed? @muratg

**Comment by shanselman** [comment]
My bad. It's that console logger is "Warning" by default in the templates.

@rustd let's change that to Info.

**Comment by muratg** [comment]
Ugh templates. https://github.com/aspnet/Templates/issues/66
