### ISSUE TITLE
KPM pack --no-source creates the src folder under the approot folder

### ISSUE THREAD

**Issue by ianhong** [aspnet/KRuntime#861]
KPM pack --no-source creates the src folder under the approot folder. I'm not sure if this is an expected behavior. 

If it is, I think we should change its name to something else to match the option, Precompile during publishing' in VS. 

I think this name, no-source, can be confused if it still generates all the source files..

**Comment by Praburaj** [comment]
I cant seem to reproduce this issue. @ianhong are you able to reproduce this issue?

**Comment by ianhong** [comment]
@ChengTian tried to repro this issue, but he coudln't. I think this issue has been fixed after I reported the problem.

**Comment by Praburaj** [comment]
Cool. Thanks closing the issue.
