### ISSUE TITLE
Rename 'sources' in global.json to something else (e.g. 'projectSearchPaths')

### ISSUE THREAD

**Issue by akoeplinger** [aspnet/KRuntime#925]
(based on today's discussion on JabbR)

In global.json the `sources` key is used to specify paths where the K runtime is looking for projects. This is easily confused with the `sources` section in project.json and also doesn't make it clear that you should be specifying the folder **above** project.json there.

Proposal: rename `sources` to `projectSearchPaths` in global.json, to clear up the confusion.

**Comment by davidfowl** [comment]
@akoeplinger we've renamed it to projects
