### ISSUE TITLE
Command k crossgen is broken

### ISSUE THREAD

**Issue by troydai** [aspnet/KRuntime#929]
With the update of `k.cmd` in https://github.com/aspnet/KRuntime/commit/29e6e8a10f4dfff004da9510d4f634070a6d6430, the `k crossgen` is never channeled to `k-crossgen.cmd` that essentially breaks steps in `kvm.ps1` (https://github.com/aspnet/kvm/blob/dev/src/kvm.ps1#L376).

In addition, parameter `--appbase` is missing from the `k-crossgen.cmd` also breaks the scenario even user invoke `k-crossgen.cmd` directly.

**Comment by Praburaj** [comment]
@troydai Is there any more action item on this bug? Can this be closed?

**Comment by troydai** [comment]
I think so.
