### ISSUE TITLE
kruntime in Local System account

### ISSUE THREAD

**Issue by RouR** [aspnet/KRuntime#941]
>kvm upgrade 
>This command will download the specified version of the K Runtime Environment (KRE), and put it on your **user profile** ready to use. 

Impossible run it from Local System account.

It necessary for Jenkins service, which run from that account. In jenkins i have job with "execute windows batch command = kvm upgrade & kpm restore & START k web " for run my web application and testing it

(Or maybe you know better solution for test it in jenkins)

**Comment by muratg** [comment]
Closing this for now.
