### ISSUE TITLE
BUG: compilation (kpm build) fails with CS0009 when assembly has .dll resources

### ISSUE THREAD

**Issue by giggio** [aspnet/KRuntime#973]
Steps to repro:

1. On VS 2015, create a new ASP.NET Class Library
2. Add a reference to Selenium.Webdriver (I used 2.44.0.0)
3. If you build on VS or `kpm build` it will fail with CS0009.

Error on `kpm build`:

````
error CS0009: Metadata file '<in-memory assembly>' could not be opened -- Image is either too small or contains an invalid byte offset or count.
error CS0009: Metadata file '<in-memory assembly>' could not be opened -- Image is too small.
````

VS is more specific, it points to the exact file in the artifacts folder, and this file is NOT a .NET assembly:

````
Metadata file '<projfolder>\artifacts\obj\ClassLibrary1\Debug\ProjectRawReferences\ASP.NET 5.0\WebDriver.FirefoxNoFocus.x64.dll' could not be opened -- Image is either too small or contains an invalid byte offset or count.	ClassLibrary1.ASP.NET 5.0		1
````

I am not sure exactly what is going on, what I do know is that this does not cause an error when building on non-aspnet5 class library. If there is a workaround at this moment, please let me know.

**Comment by carolynvs** [comment]
@giggio Thanks for the new packages, they are very helpful.

**Comment by davidfowl** [comment]
Fix the in latest builds
